services:
  front:
    container_name: front
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./src/front:/nuxt/app
      - /nuxt/app/node_modules
      - front_node_modules:/nuxt/app/node_modules
    networks:
      - app
  database:
    image: mysql:8.4
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app
networks:
  app:
    driver: bridge

volumes:
  mysql-data:
  front_node_modules:
