services:
  front:
    container_name: front
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/front:/nuxt/app:rw
    networks:
      - app
networks:
  app:
    driver: bridge
